/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type GetProductsRequest = {
    /**
     * IntegrationOS API key
     */
    xIntegrationosSecret: string;
    /**
     * The unique identifier of a Connected Account
     */
    xIntegrationosConnectionKey: string;
};

export enum GetProductsStatusCode {
    TwoHundred = 200,
    FourHundred = 400,
    FiveHundred = 500,
}

export type GetProductsPrices = {
    amount?: number | undefined;
    currency?: string | undefined;
};

export enum GetProductsSkuValidation {
    GlobalUnique = "global_unique",
    LocalUnique = "local_unique",
    None = "none",
}

export enum GetProductsMimeType {
    ImageJpeg = "image/jpeg",
    ImagePng = "image/png",
    ImageGif = "image/gif",
    ImageSvgPlusXml = "image/svg+xml",
    ImageWebp = "image/webp",
}

export type GetProductsImages = {
    id?: string | undefined;
    src?: string | undefined;
    altText?: string | undefined;
    width?: number | undefined;
    height?: number | undefined;
    thumbnailSrc?: string | undefined;
    caption?: string | undefined;
    title?: string | undefined;
    mimeType?: GetProductsMimeType | undefined;
    tags?: Array<string> | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
    active?: boolean | undefined;
    deleted?: boolean | undefined;
};

export type GetProductsProductsDimensions = {};

export enum GetProductsProductsStatus {
    Active = "ACTIVE",
    Inactive = "INACTIVE",
    OutOfStock = "OUT_OF_STOCK",
    Discontinued = "DISCONTINUED",
}

export type GetProductsVariants = {
    id?: string | undefined;
    productId?: number | undefined;
    title?: string | undefined;
    sku?: string | undefined;
    price?: number | undefined;
    compareAtPrice?: number | undefined;
    inventoryQuantity?: number | undefined;
    weight?: number | undefined;
    weightUnit?: string | undefined;
    requiresShipping?: boolean | undefined;
    taxable?: boolean | undefined;
    barcode?: string | undefined;
    imageId?: number | undefined;
    dimensions?: GetProductsProductsDimensions | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
    status?: GetProductsProductsStatus | undefined;
    active?: boolean | undefined;
    deleted?: boolean | undefined;
};

export type GetProductsOptions = {
    id?: string | undefined;
    productId?: number | undefined;
    name?: string | undefined;
    values?: Array<string> | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
};

export enum GetProductsProductsType {
    Home = "home",
    Work = "work",
    Other = "other",
}

export type GetProductsGeoLocation = {
    latitude?: number | undefined;
    longitude?: number | undefined;
    altitude?: number | undefined;
    accuracy?: number | undefined;
    altitudeAccuracy?: number | undefined;
    heading?: number | undefined;
    speed?: number | undefined;
    timestamp?: number | undefined;
};

export enum GetProductsProductsResponseFieldType {
    Text = "text",
    Number = "number",
    Date = "date",
    Boolean = "boolean",
    Enum = "enum",
    Json = "json",
    Array = "array",
}

export type GetProductsProductsResponseCustomFields = {
    id?: string | undefined;
    fieldName?: string | undefined;
    fieldValue?: string | undefined;
    fieldType?: GetProductsProductsResponseFieldType | undefined;
};

export type GetProductsAddress = {
    id?: string | undefined;
    contactId?: string | undefined;
    accountId?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    name?: string | undefined;
    companyName?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    street?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    province?: string | undefined;
    region?: string | undefined;
    postalCode?: string | undefined;
    postalCodeExtension?: string | undefined;
    country?: string | undefined;
    countryCode?: string | undefined;
    type?: GetProductsProductsType | undefined;
    geoLocation?: GetProductsGeoLocation | undefined;
    customFields?: Array<GetProductsProductsResponseCustomFields> | undefined;
    subdivisionCode?: string | undefined;
};

export type GetProductsContactInformation = {};

export enum GetProductsType {
    Warehouse = "WAREHOUSE",
    RetailStore = "RETAIL_STORE",
    DistributionCenter = "DISTRIBUTION_CENTER",
    DropShipper = "DROP_SHIPPER",
    Other = "OTHER",
}

export type GetProductsInventoryLocation = {
    locationId?: string | undefined;
    name?: string | undefined;
    address?: GetProductsAddress | undefined;
    contactInformation?: Array<GetProductsContactInformation> | undefined;
    type?: GetProductsType | undefined;
    quantity?: number | undefined;
    operationalHours?: string | undefined;
    isActive?: boolean | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
    deleted?: boolean | undefined;
};

export type GetProductsDimensions = {
    height?: number | undefined;
    length?: number | undefined;
    width?: number | undefined;
};

export enum GetProductsFieldType {
    Text = "text",
    Number = "number",
    Date = "date",
    Boolean = "boolean",
    Enum = "enum",
    Json = "json",
    Array = "array",
}

export type GetProductsCustomFields = {
    id?: string | undefined;
    fieldName?: string | undefined;
    fieldValue?: string | undefined;
    fieldType?: GetProductsFieldType | undefined;
};

export type GetProductsMetadata = {};

export type GetProductsAssociatedWith = {};

export type GetProductsPermissions = {};

export type GetProductsDownloadFiles = {
    id?: string | undefined;
    fileName?: string | undefined;
    fileSize?: number | undefined;
    fileType?: string | undefined;
    url?: string | undefined;
    thumbnailUrl?: string | undefined;
    previewUrl?: string | undefined;
    content?: string | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
    metadata?: GetProductsMetadata | undefined;
    associatedWith?: GetProductsAssociatedWith | undefined;
    permissions?: GetProductsPermissions | undefined;
};

export enum GetProductsStatus {
    Active = "active",
    Archived = "archived",
    Draft = "draft",
    Deleted = "deleted",
}

export type GetProductsTaxDetails = {};

export enum GetProductsProductsFieldType {
    Text = "text",
    Number = "number",
    Date = "date",
    Boolean = "boolean",
    Enum = "enum",
    Json = "json",
    Array = "array",
}

export type GetProductsProductsCustomFields = {
    id?: string | undefined;
    fieldName?: string | undefined;
    fieldValue?: string | undefined;
    fieldType?: GetProductsProductsFieldType | undefined;
};

export type GetProductsTax = {
    taxCode?: string | undefined;
    taxable?: boolean | undefined;
    taxRate?: number | undefined;
    currency?: string | undefined;
    country?: string | undefined;
    region?: string | undefined;
    description?: string | undefined;
    taxAmount?: number | undefined;
    taxDetails?: GetProductsTaxDetails | undefined;
    customFields?: Array<GetProductsProductsCustomFields> | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
    active?: boolean | undefined;
    deleted?: boolean | undefined;
};

export type GetProductsLocalizations = {
    locale?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    metaTitle?: string | undefined;
    metaDescription?: string | undefined;
};

export type GetProductsUnified = {
    id?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    prices?: Array<GetProductsPrices> | undefined;
    sku?: string | undefined;
    skuValidation?: GetProductsSkuValidation | undefined;
    images?: Array<GetProductsImages> | undefined;
    variants?: Array<GetProductsVariants> | undefined;
    options?: Array<GetProductsOptions> | undefined;
    categories?: Array<string> | undefined;
    tags?: Array<string> | undefined;
    vendor?: string | undefined;
    inventoryQuantity?: number | undefined;
    inventoryLocation?: GetProductsInventoryLocation | undefined;
    availableForSale?: boolean | undefined;
    dimensions?: GetProductsDimensions | undefined;
    weight?: number | undefined;
    weightUnit?: string | undefined;
    type?: string | undefined;
    metaTitle?: string | undefined;
    metaDescription?: string | undefined;
    seoKeywords?: Array<string> | undefined;
    slug?: string | undefined;
    customFields?: Array<GetProductsCustomFields> | undefined;
    isDownloadable?: boolean | undefined;
    downloadFiles?: Array<GetProductsDownloadFiles> | undefined;
    relatedProducts?: Array<string> | undefined;
    createdAt?: number | undefined;
    updatedAt?: number | undefined;
    publishedAt?: number | undefined;
    status?: GetProductsStatus | undefined;
    tax?: GetProductsTax | undefined;
    localizations?: Array<GetProductsLocalizations> | undefined;
};

export type GetProductsPassthrough = {};

export type GetProductsCache = {
    hit?: boolean | undefined;
    ttl?: number | undefined;
    key?: string | undefined;
};

export type GetProductsMeta = {
    timestamp?: number | undefined;
    latency?: number | undefined;
    platformRateLimitRemaining?: number | undefined;
    rateLimitRemaining?: number | undefined;
    cache?: GetProductsCache | undefined;
    transactionKey?: string | undefined;
    txn?: string | undefined;
    platform?: string | undefined;
    platformVersion?: string | undefined;
    connectionDefinitionKey?: string | undefined;
    action?: string | undefined;
    commonModel?: string | undefined;
    commonModelVersion?: string | undefined;
    connectionKey?: string | undefined;
    hash?: string | undefined;
    heartbeats?: Array<string> | undefined;
    totalTransactions?: number | undefined;
};

export type GetProductsPagination = {
    cursor?: string | undefined;
    limit?: number | undefined;
};

/**
 * Successful response
 */
export type GetProductsResponseBody = {
    status?: string | undefined;
    statusCode?: GetProductsStatusCode | undefined;
    unified?: Array<GetProductsUnified> | undefined;
    passthrough?: GetProductsPassthrough | undefined;
    meta?: GetProductsMeta | undefined;
    pagination?: GetProductsPagination | undefined;
};

export type GetProductsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful response
     */
    object?: GetProductsResponseBody | undefined;
};

/** @internal */
export namespace GetProductsRequest$ {
    export type Inbound = {
        "X-INTEGRATIONOS-SECRET": string;
        "X-INTEGRATIONOS-CONNECTION-KEY": string;
    };

    export const inboundSchema: z.ZodType<GetProductsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            "X-INTEGRATIONOS-SECRET": z.string(),
            "X-INTEGRATIONOS-CONNECTION-KEY": z.string(),
        })
        .transform((v) => {
            return {
                xIntegrationosSecret: v["X-INTEGRATIONOS-SECRET"],
                xIntegrationosConnectionKey: v["X-INTEGRATIONOS-CONNECTION-KEY"],
            };
        });

    export type Outbound = {
        "X-INTEGRATIONOS-SECRET": string;
        "X-INTEGRATIONOS-CONNECTION-KEY": string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsRequest> = z
        .object({
            xIntegrationosSecret: z.string(),
            xIntegrationosConnectionKey: z.string(),
        })
        .transform((v) => {
            return {
                "X-INTEGRATIONOS-SECRET": v.xIntegrationosSecret,
                "X-INTEGRATIONOS-CONNECTION-KEY": v.xIntegrationosConnectionKey,
            };
        });
}

/** @internal */
export const GetProductsStatusCode$ = z.nativeEnum(GetProductsStatusCode);

/** @internal */
export namespace GetProductsPrices$ {
    export type Inbound = {
        amount?: number | undefined;
        currency?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsPrices, z.ZodTypeDef, Inbound> = z
        .object({
            amount: z.number().optional(),
            currency: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.amount === undefined ? null : { amount: v.amount }),
                ...(v.currency === undefined ? null : { currency: v.currency }),
            };
        });

    export type Outbound = {
        amount?: number | undefined;
        currency?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsPrices> = z
        .object({
            amount: z.number().optional(),
            currency: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.amount === undefined ? null : { amount: v.amount }),
                ...(v.currency === undefined ? null : { currency: v.currency }),
            };
        });
}

/** @internal */
export const GetProductsSkuValidation$ = z.nativeEnum(GetProductsSkuValidation);

/** @internal */
export const GetProductsMimeType$ = z.nativeEnum(GetProductsMimeType);

/** @internal */
export namespace GetProductsImages$ {
    export type Inbound = {
        id?: string | undefined;
        src?: string | undefined;
        altText?: string | undefined;
        width?: number | undefined;
        height?: number | undefined;
        thumbnailSrc?: string | undefined;
        caption?: string | undefined;
        title?: string | undefined;
        mimeType?: GetProductsMimeType | undefined;
        tags?: Array<string> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        active?: boolean | undefined;
        deleted?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsImages, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            src: z.string().optional(),
            altText: z.string().optional(),
            width: z.number().optional(),
            height: z.number().optional(),
            thumbnailSrc: z.string().optional(),
            caption: z.string().optional(),
            title: z.string().optional(),
            mimeType: GetProductsMimeType$.optional(),
            tags: z.array(z.string()).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            active: z.boolean().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.src === undefined ? null : { src: v.src }),
                ...(v.altText === undefined ? null : { altText: v.altText }),
                ...(v.width === undefined ? null : { width: v.width }),
                ...(v.height === undefined ? null : { height: v.height }),
                ...(v.thumbnailSrc === undefined ? null : { thumbnailSrc: v.thumbnailSrc }),
                ...(v.caption === undefined ? null : { caption: v.caption }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.mimeType === undefined ? null : { mimeType: v.mimeType }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.active === undefined ? null : { active: v.active }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        src?: string | undefined;
        altText?: string | undefined;
        width?: number | undefined;
        height?: number | undefined;
        thumbnailSrc?: string | undefined;
        caption?: string | undefined;
        title?: string | undefined;
        mimeType?: GetProductsMimeType | undefined;
        tags?: Array<string> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        active?: boolean | undefined;
        deleted?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsImages> = z
        .object({
            id: z.string().optional(),
            src: z.string().optional(),
            altText: z.string().optional(),
            width: z.number().optional(),
            height: z.number().optional(),
            thumbnailSrc: z.string().optional(),
            caption: z.string().optional(),
            title: z.string().optional(),
            mimeType: GetProductsMimeType$.optional(),
            tags: z.array(z.string()).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            active: z.boolean().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.src === undefined ? null : { src: v.src }),
                ...(v.altText === undefined ? null : { altText: v.altText }),
                ...(v.width === undefined ? null : { width: v.width }),
                ...(v.height === undefined ? null : { height: v.height }),
                ...(v.thumbnailSrc === undefined ? null : { thumbnailSrc: v.thumbnailSrc }),
                ...(v.caption === undefined ? null : { caption: v.caption }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.mimeType === undefined ? null : { mimeType: v.mimeType }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.active === undefined ? null : { active: v.active }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });
}

/** @internal */
export namespace GetProductsProductsDimensions$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsProductsDimensions, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsProductsDimensions> =
        z.object({});
}

/** @internal */
export const GetProductsProductsStatus$ = z.nativeEnum(GetProductsProductsStatus);

/** @internal */
export namespace GetProductsVariants$ {
    export type Inbound = {
        id?: string | undefined;
        productId?: number | undefined;
        title?: string | undefined;
        sku?: string | undefined;
        price?: number | undefined;
        compareAtPrice?: number | undefined;
        inventoryQuantity?: number | undefined;
        weight?: number | undefined;
        weightUnit?: string | undefined;
        requiresShipping?: boolean | undefined;
        taxable?: boolean | undefined;
        barcode?: string | undefined;
        imageId?: number | undefined;
        dimensions?: GetProductsProductsDimensions$.Inbound | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        status?: GetProductsProductsStatus | undefined;
        active?: boolean | undefined;
        deleted?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsVariants, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            productId: z.number().optional(),
            title: z.string().optional(),
            sku: z.string().optional(),
            price: z.number().optional(),
            compareAtPrice: z.number().optional(),
            inventoryQuantity: z.number().optional(),
            weight: z.number().optional(),
            weightUnit: z.string().optional(),
            requiresShipping: z.boolean().optional(),
            taxable: z.boolean().optional(),
            barcode: z.string().optional(),
            imageId: z.number().optional(),
            dimensions: z.lazy(() => GetProductsProductsDimensions$.inboundSchema).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            status: GetProductsProductsStatus$.optional(),
            active: z.boolean().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.productId === undefined ? null : { productId: v.productId }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.sku === undefined ? null : { sku: v.sku }),
                ...(v.price === undefined ? null : { price: v.price }),
                ...(v.compareAtPrice === undefined ? null : { compareAtPrice: v.compareAtPrice }),
                ...(v.inventoryQuantity === undefined
                    ? null
                    : { inventoryQuantity: v.inventoryQuantity }),
                ...(v.weight === undefined ? null : { weight: v.weight }),
                ...(v.weightUnit === undefined ? null : { weightUnit: v.weightUnit }),
                ...(v.requiresShipping === undefined
                    ? null
                    : { requiresShipping: v.requiresShipping }),
                ...(v.taxable === undefined ? null : { taxable: v.taxable }),
                ...(v.barcode === undefined ? null : { barcode: v.barcode }),
                ...(v.imageId === undefined ? null : { imageId: v.imageId }),
                ...(v.dimensions === undefined ? null : { dimensions: v.dimensions }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.active === undefined ? null : { active: v.active }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        productId?: number | undefined;
        title?: string | undefined;
        sku?: string | undefined;
        price?: number | undefined;
        compareAtPrice?: number | undefined;
        inventoryQuantity?: number | undefined;
        weight?: number | undefined;
        weightUnit?: string | undefined;
        requiresShipping?: boolean | undefined;
        taxable?: boolean | undefined;
        barcode?: string | undefined;
        imageId?: number | undefined;
        dimensions?: GetProductsProductsDimensions$.Outbound | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        status?: GetProductsProductsStatus | undefined;
        active?: boolean | undefined;
        deleted?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsVariants> = z
        .object({
            id: z.string().optional(),
            productId: z.number().optional(),
            title: z.string().optional(),
            sku: z.string().optional(),
            price: z.number().optional(),
            compareAtPrice: z.number().optional(),
            inventoryQuantity: z.number().optional(),
            weight: z.number().optional(),
            weightUnit: z.string().optional(),
            requiresShipping: z.boolean().optional(),
            taxable: z.boolean().optional(),
            barcode: z.string().optional(),
            imageId: z.number().optional(),
            dimensions: z.lazy(() => GetProductsProductsDimensions$.outboundSchema).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            status: GetProductsProductsStatus$.optional(),
            active: z.boolean().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.productId === undefined ? null : { productId: v.productId }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.sku === undefined ? null : { sku: v.sku }),
                ...(v.price === undefined ? null : { price: v.price }),
                ...(v.compareAtPrice === undefined ? null : { compareAtPrice: v.compareAtPrice }),
                ...(v.inventoryQuantity === undefined
                    ? null
                    : { inventoryQuantity: v.inventoryQuantity }),
                ...(v.weight === undefined ? null : { weight: v.weight }),
                ...(v.weightUnit === undefined ? null : { weightUnit: v.weightUnit }),
                ...(v.requiresShipping === undefined
                    ? null
                    : { requiresShipping: v.requiresShipping }),
                ...(v.taxable === undefined ? null : { taxable: v.taxable }),
                ...(v.barcode === undefined ? null : { barcode: v.barcode }),
                ...(v.imageId === undefined ? null : { imageId: v.imageId }),
                ...(v.dimensions === undefined ? null : { dimensions: v.dimensions }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.active === undefined ? null : { active: v.active }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });
}

/** @internal */
export namespace GetProductsOptions$ {
    export type Inbound = {
        id?: string | undefined;
        productId?: number | undefined;
        name?: string | undefined;
        values?: Array<string> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsOptions, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            productId: z.number().optional(),
            name: z.string().optional(),
            values: z.array(z.string()).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.productId === undefined ? null : { productId: v.productId }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.values === undefined ? null : { values: v.values }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        productId?: number | undefined;
        name?: string | undefined;
        values?: Array<string> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsOptions> = z
        .object({
            id: z.string().optional(),
            productId: z.number().optional(),
            name: z.string().optional(),
            values: z.array(z.string()).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.productId === undefined ? null : { productId: v.productId }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.values === undefined ? null : { values: v.values }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
            };
        });
}

/** @internal */
export const GetProductsProductsType$ = z.nativeEnum(GetProductsProductsType);

/** @internal */
export namespace GetProductsGeoLocation$ {
    export type Inbound = {
        latitude?: number | undefined;
        longitude?: number | undefined;
        altitude?: number | undefined;
        accuracy?: number | undefined;
        altitudeAccuracy?: number | undefined;
        heading?: number | undefined;
        speed?: number | undefined;
        timestamp?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsGeoLocation, z.ZodTypeDef, Inbound> = z
        .object({
            latitude: z.number().optional(),
            longitude: z.number().optional(),
            altitude: z.number().optional(),
            accuracy: z.number().optional(),
            altitudeAccuracy: z.number().optional(),
            heading: z.number().optional(),
            speed: z.number().optional(),
            timestamp: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.latitude === undefined ? null : { latitude: v.latitude }),
                ...(v.longitude === undefined ? null : { longitude: v.longitude }),
                ...(v.altitude === undefined ? null : { altitude: v.altitude }),
                ...(v.accuracy === undefined ? null : { accuracy: v.accuracy }),
                ...(v.altitudeAccuracy === undefined
                    ? null
                    : { altitudeAccuracy: v.altitudeAccuracy }),
                ...(v.heading === undefined ? null : { heading: v.heading }),
                ...(v.speed === undefined ? null : { speed: v.speed }),
                ...(v.timestamp === undefined ? null : { timestamp: v.timestamp }),
            };
        });

    export type Outbound = {
        latitude?: number | undefined;
        longitude?: number | undefined;
        altitude?: number | undefined;
        accuracy?: number | undefined;
        altitudeAccuracy?: number | undefined;
        heading?: number | undefined;
        speed?: number | undefined;
        timestamp?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsGeoLocation> = z
        .object({
            latitude: z.number().optional(),
            longitude: z.number().optional(),
            altitude: z.number().optional(),
            accuracy: z.number().optional(),
            altitudeAccuracy: z.number().optional(),
            heading: z.number().optional(),
            speed: z.number().optional(),
            timestamp: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.latitude === undefined ? null : { latitude: v.latitude }),
                ...(v.longitude === undefined ? null : { longitude: v.longitude }),
                ...(v.altitude === undefined ? null : { altitude: v.altitude }),
                ...(v.accuracy === undefined ? null : { accuracy: v.accuracy }),
                ...(v.altitudeAccuracy === undefined
                    ? null
                    : { altitudeAccuracy: v.altitudeAccuracy }),
                ...(v.heading === undefined ? null : { heading: v.heading }),
                ...(v.speed === undefined ? null : { speed: v.speed }),
                ...(v.timestamp === undefined ? null : { timestamp: v.timestamp }),
            };
        });
}

/** @internal */
export const GetProductsProductsResponseFieldType$ = z.nativeEnum(
    GetProductsProductsResponseFieldType
);

/** @internal */
export namespace GetProductsProductsResponseCustomFields$ {
    export type Inbound = {
        id?: string | undefined;
        fieldName?: string | undefined;
        fieldValue?: string | undefined;
        fieldType?: GetProductsProductsResponseFieldType | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetProductsProductsResponseCustomFields,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            id: z.string().optional(),
            fieldName: z.string().optional(),
            fieldValue: z.string().optional(),
            fieldType: GetProductsProductsResponseFieldType$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fieldName === undefined ? null : { fieldName: v.fieldName }),
                ...(v.fieldValue === undefined ? null : { fieldValue: v.fieldValue }),
                ...(v.fieldType === undefined ? null : { fieldType: v.fieldType }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        fieldName?: string | undefined;
        fieldValue?: string | undefined;
        fieldType?: GetProductsProductsResponseFieldType | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetProductsProductsResponseCustomFields
    > = z
        .object({
            id: z.string().optional(),
            fieldName: z.string().optional(),
            fieldValue: z.string().optional(),
            fieldType: GetProductsProductsResponseFieldType$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fieldName === undefined ? null : { fieldName: v.fieldName }),
                ...(v.fieldValue === undefined ? null : { fieldValue: v.fieldValue }),
                ...(v.fieldType === undefined ? null : { fieldType: v.fieldType }),
            };
        });
}

/** @internal */
export namespace GetProductsAddress$ {
    export type Inbound = {
        id?: string | undefined;
        contactId?: string | undefined;
        accountId?: string | undefined;
        firstName?: string | undefined;
        lastName?: string | undefined;
        name?: string | undefined;
        companyName?: string | undefined;
        email?: string | undefined;
        phone?: string | undefined;
        street?: string | undefined;
        addressLine2?: string | undefined;
        city?: string | undefined;
        province?: string | undefined;
        region?: string | undefined;
        postalCode?: string | undefined;
        postalCodeExtension?: string | undefined;
        country?: string | undefined;
        countryCode?: string | undefined;
        type?: GetProductsProductsType | undefined;
        geoLocation?: GetProductsGeoLocation$.Inbound | undefined;
        customFields?: Array<GetProductsProductsResponseCustomFields$.Inbound> | undefined;
        subdivisionCode?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsAddress, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            contactId: z.string().optional(),
            accountId: z.string().optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            name: z.string().optional(),
            companyName: z.string().optional(),
            email: z.string().optional(),
            phone: z.string().optional(),
            street: z.string().optional(),
            addressLine2: z.string().optional(),
            city: z.string().optional(),
            province: z.string().optional(),
            region: z.string().optional(),
            postalCode: z.string().optional(),
            postalCodeExtension: z.string().optional(),
            country: z.string().optional(),
            countryCode: z.string().optional(),
            type: GetProductsProductsType$.optional(),
            geoLocation: z.lazy(() => GetProductsGeoLocation$.inboundSchema).optional(),
            customFields: z
                .array(z.lazy(() => GetProductsProductsResponseCustomFields$.inboundSchema))
                .optional(),
            subdivisionCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.contactId === undefined ? null : { contactId: v.contactId }),
                ...(v.accountId === undefined ? null : { accountId: v.accountId }),
                ...(v.firstName === undefined ? null : { firstName: v.firstName }),
                ...(v.lastName === undefined ? null : { lastName: v.lastName }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.companyName === undefined ? null : { companyName: v.companyName }),
                ...(v.email === undefined ? null : { email: v.email }),
                ...(v.phone === undefined ? null : { phone: v.phone }),
                ...(v.street === undefined ? null : { street: v.street }),
                ...(v.addressLine2 === undefined ? null : { addressLine2: v.addressLine2 }),
                ...(v.city === undefined ? null : { city: v.city }),
                ...(v.province === undefined ? null : { province: v.province }),
                ...(v.region === undefined ? null : { region: v.region }),
                ...(v.postalCode === undefined ? null : { postalCode: v.postalCode }),
                ...(v.postalCodeExtension === undefined
                    ? null
                    : { postalCodeExtension: v.postalCodeExtension }),
                ...(v.country === undefined ? null : { country: v.country }),
                ...(v.countryCode === undefined ? null : { countryCode: v.countryCode }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.geoLocation === undefined ? null : { geoLocation: v.geoLocation }),
                ...(v.customFields === undefined ? null : { customFields: v.customFields }),
                ...(v.subdivisionCode === undefined
                    ? null
                    : { subdivisionCode: v.subdivisionCode }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        contactId?: string | undefined;
        accountId?: string | undefined;
        firstName?: string | undefined;
        lastName?: string | undefined;
        name?: string | undefined;
        companyName?: string | undefined;
        email?: string | undefined;
        phone?: string | undefined;
        street?: string | undefined;
        addressLine2?: string | undefined;
        city?: string | undefined;
        province?: string | undefined;
        region?: string | undefined;
        postalCode?: string | undefined;
        postalCodeExtension?: string | undefined;
        country?: string | undefined;
        countryCode?: string | undefined;
        type?: GetProductsProductsType | undefined;
        geoLocation?: GetProductsGeoLocation$.Outbound | undefined;
        customFields?: Array<GetProductsProductsResponseCustomFields$.Outbound> | undefined;
        subdivisionCode?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsAddress> = z
        .object({
            id: z.string().optional(),
            contactId: z.string().optional(),
            accountId: z.string().optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            name: z.string().optional(),
            companyName: z.string().optional(),
            email: z.string().optional(),
            phone: z.string().optional(),
            street: z.string().optional(),
            addressLine2: z.string().optional(),
            city: z.string().optional(),
            province: z.string().optional(),
            region: z.string().optional(),
            postalCode: z.string().optional(),
            postalCodeExtension: z.string().optional(),
            country: z.string().optional(),
            countryCode: z.string().optional(),
            type: GetProductsProductsType$.optional(),
            geoLocation: z.lazy(() => GetProductsGeoLocation$.outboundSchema).optional(),
            customFields: z
                .array(z.lazy(() => GetProductsProductsResponseCustomFields$.outboundSchema))
                .optional(),
            subdivisionCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.contactId === undefined ? null : { contactId: v.contactId }),
                ...(v.accountId === undefined ? null : { accountId: v.accountId }),
                ...(v.firstName === undefined ? null : { firstName: v.firstName }),
                ...(v.lastName === undefined ? null : { lastName: v.lastName }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.companyName === undefined ? null : { companyName: v.companyName }),
                ...(v.email === undefined ? null : { email: v.email }),
                ...(v.phone === undefined ? null : { phone: v.phone }),
                ...(v.street === undefined ? null : { street: v.street }),
                ...(v.addressLine2 === undefined ? null : { addressLine2: v.addressLine2 }),
                ...(v.city === undefined ? null : { city: v.city }),
                ...(v.province === undefined ? null : { province: v.province }),
                ...(v.region === undefined ? null : { region: v.region }),
                ...(v.postalCode === undefined ? null : { postalCode: v.postalCode }),
                ...(v.postalCodeExtension === undefined
                    ? null
                    : { postalCodeExtension: v.postalCodeExtension }),
                ...(v.country === undefined ? null : { country: v.country }),
                ...(v.countryCode === undefined ? null : { countryCode: v.countryCode }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.geoLocation === undefined ? null : { geoLocation: v.geoLocation }),
                ...(v.customFields === undefined ? null : { customFields: v.customFields }),
                ...(v.subdivisionCode === undefined
                    ? null
                    : { subdivisionCode: v.subdivisionCode }),
            };
        });
}

/** @internal */
export namespace GetProductsContactInformation$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsContactInformation, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsContactInformation> =
        z.object({});
}

/** @internal */
export const GetProductsType$ = z.nativeEnum(GetProductsType);

/** @internal */
export namespace GetProductsInventoryLocation$ {
    export type Inbound = {
        locationId?: string | undefined;
        name?: string | undefined;
        address?: GetProductsAddress$.Inbound | undefined;
        contactInformation?: Array<GetProductsContactInformation$.Inbound> | undefined;
        type?: GetProductsType | undefined;
        quantity?: number | undefined;
        operationalHours?: string | undefined;
        isActive?: boolean | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        deleted?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsInventoryLocation, z.ZodTypeDef, Inbound> = z
        .object({
            locationId: z.string().optional(),
            name: z.string().optional(),
            address: z.lazy(() => GetProductsAddress$.inboundSchema).optional(),
            contactInformation: z
                .array(z.lazy(() => GetProductsContactInformation$.inboundSchema))
                .optional(),
            type: GetProductsType$.optional(),
            quantity: z.number().optional(),
            operationalHours: z.string().optional(),
            isActive: z.boolean().optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.locationId === undefined ? null : { locationId: v.locationId }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.address === undefined ? null : { address: v.address }),
                ...(v.contactInformation === undefined
                    ? null
                    : { contactInformation: v.contactInformation }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.quantity === undefined ? null : { quantity: v.quantity }),
                ...(v.operationalHours === undefined
                    ? null
                    : { operationalHours: v.operationalHours }),
                ...(v.isActive === undefined ? null : { isActive: v.isActive }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });

    export type Outbound = {
        locationId?: string | undefined;
        name?: string | undefined;
        address?: GetProductsAddress$.Outbound | undefined;
        contactInformation?: Array<GetProductsContactInformation$.Outbound> | undefined;
        type?: GetProductsType | undefined;
        quantity?: number | undefined;
        operationalHours?: string | undefined;
        isActive?: boolean | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        deleted?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsInventoryLocation> = z
        .object({
            locationId: z.string().optional(),
            name: z.string().optional(),
            address: z.lazy(() => GetProductsAddress$.outboundSchema).optional(),
            contactInformation: z
                .array(z.lazy(() => GetProductsContactInformation$.outboundSchema))
                .optional(),
            type: GetProductsType$.optional(),
            quantity: z.number().optional(),
            operationalHours: z.string().optional(),
            isActive: z.boolean().optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.locationId === undefined ? null : { locationId: v.locationId }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.address === undefined ? null : { address: v.address }),
                ...(v.contactInformation === undefined
                    ? null
                    : { contactInformation: v.contactInformation }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.quantity === undefined ? null : { quantity: v.quantity }),
                ...(v.operationalHours === undefined
                    ? null
                    : { operationalHours: v.operationalHours }),
                ...(v.isActive === undefined ? null : { isActive: v.isActive }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });
}

/** @internal */
export namespace GetProductsDimensions$ {
    export type Inbound = {
        height?: number | undefined;
        length?: number | undefined;
        width?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsDimensions, z.ZodTypeDef, Inbound> = z
        .object({
            height: z.number().optional(),
            length: z.number().optional(),
            width: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.height === undefined ? null : { height: v.height }),
                ...(v.length === undefined ? null : { length: v.length }),
                ...(v.width === undefined ? null : { width: v.width }),
            };
        });

    export type Outbound = {
        height?: number | undefined;
        length?: number | undefined;
        width?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsDimensions> = z
        .object({
            height: z.number().optional(),
            length: z.number().optional(),
            width: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.height === undefined ? null : { height: v.height }),
                ...(v.length === undefined ? null : { length: v.length }),
                ...(v.width === undefined ? null : { width: v.width }),
            };
        });
}

/** @internal */
export const GetProductsFieldType$ = z.nativeEnum(GetProductsFieldType);

/** @internal */
export namespace GetProductsCustomFields$ {
    export type Inbound = {
        id?: string | undefined;
        fieldName?: string | undefined;
        fieldValue?: string | undefined;
        fieldType?: GetProductsFieldType | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsCustomFields, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            fieldName: z.string().optional(),
            fieldValue: z.string().optional(),
            fieldType: GetProductsFieldType$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fieldName === undefined ? null : { fieldName: v.fieldName }),
                ...(v.fieldValue === undefined ? null : { fieldValue: v.fieldValue }),
                ...(v.fieldType === undefined ? null : { fieldType: v.fieldType }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        fieldName?: string | undefined;
        fieldValue?: string | undefined;
        fieldType?: GetProductsFieldType | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsCustomFields> = z
        .object({
            id: z.string().optional(),
            fieldName: z.string().optional(),
            fieldValue: z.string().optional(),
            fieldType: GetProductsFieldType$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fieldName === undefined ? null : { fieldName: v.fieldName }),
                ...(v.fieldValue === undefined ? null : { fieldValue: v.fieldValue }),
                ...(v.fieldType === undefined ? null : { fieldType: v.fieldType }),
            };
        });
}

/** @internal */
export namespace GetProductsMetadata$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsMetadata, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsMetadata> = z.object(
        {}
    );
}

/** @internal */
export namespace GetProductsAssociatedWith$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsAssociatedWith, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsAssociatedWith> =
        z.object({});
}

/** @internal */
export namespace GetProductsPermissions$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsPermissions, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsPermissions> =
        z.object({});
}

/** @internal */
export namespace GetProductsDownloadFiles$ {
    export type Inbound = {
        id?: string | undefined;
        fileName?: string | undefined;
        fileSize?: number | undefined;
        fileType?: string | undefined;
        url?: string | undefined;
        thumbnailUrl?: string | undefined;
        previewUrl?: string | undefined;
        content?: string | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        metadata?: GetProductsMetadata$.Inbound | undefined;
        associatedWith?: GetProductsAssociatedWith$.Inbound | undefined;
        permissions?: GetProductsPermissions$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsDownloadFiles, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            fileName: z.string().optional(),
            fileSize: z.number().optional(),
            fileType: z.string().optional(),
            url: z.string().optional(),
            thumbnailUrl: z.string().optional(),
            previewUrl: z.string().optional(),
            content: z.string().optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            metadata: z.lazy(() => GetProductsMetadata$.inboundSchema).optional(),
            associatedWith: z.lazy(() => GetProductsAssociatedWith$.inboundSchema).optional(),
            permissions: z.lazy(() => GetProductsPermissions$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fileName === undefined ? null : { fileName: v.fileName }),
                ...(v.fileSize === undefined ? null : { fileSize: v.fileSize }),
                ...(v.fileType === undefined ? null : { fileType: v.fileType }),
                ...(v.url === undefined ? null : { url: v.url }),
                ...(v.thumbnailUrl === undefined ? null : { thumbnailUrl: v.thumbnailUrl }),
                ...(v.previewUrl === undefined ? null : { previewUrl: v.previewUrl }),
                ...(v.content === undefined ? null : { content: v.content }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.metadata === undefined ? null : { metadata: v.metadata }),
                ...(v.associatedWith === undefined ? null : { associatedWith: v.associatedWith }),
                ...(v.permissions === undefined ? null : { permissions: v.permissions }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        fileName?: string | undefined;
        fileSize?: number | undefined;
        fileType?: string | undefined;
        url?: string | undefined;
        thumbnailUrl?: string | undefined;
        previewUrl?: string | undefined;
        content?: string | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        metadata?: GetProductsMetadata$.Outbound | undefined;
        associatedWith?: GetProductsAssociatedWith$.Outbound | undefined;
        permissions?: GetProductsPermissions$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsDownloadFiles> = z
        .object({
            id: z.string().optional(),
            fileName: z.string().optional(),
            fileSize: z.number().optional(),
            fileType: z.string().optional(),
            url: z.string().optional(),
            thumbnailUrl: z.string().optional(),
            previewUrl: z.string().optional(),
            content: z.string().optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            metadata: z.lazy(() => GetProductsMetadata$.outboundSchema).optional(),
            associatedWith: z.lazy(() => GetProductsAssociatedWith$.outboundSchema).optional(),
            permissions: z.lazy(() => GetProductsPermissions$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fileName === undefined ? null : { fileName: v.fileName }),
                ...(v.fileSize === undefined ? null : { fileSize: v.fileSize }),
                ...(v.fileType === undefined ? null : { fileType: v.fileType }),
                ...(v.url === undefined ? null : { url: v.url }),
                ...(v.thumbnailUrl === undefined ? null : { thumbnailUrl: v.thumbnailUrl }),
                ...(v.previewUrl === undefined ? null : { previewUrl: v.previewUrl }),
                ...(v.content === undefined ? null : { content: v.content }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.metadata === undefined ? null : { metadata: v.metadata }),
                ...(v.associatedWith === undefined ? null : { associatedWith: v.associatedWith }),
                ...(v.permissions === undefined ? null : { permissions: v.permissions }),
            };
        });
}

/** @internal */
export const GetProductsStatus$ = z.nativeEnum(GetProductsStatus);

/** @internal */
export namespace GetProductsTaxDetails$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsTaxDetails, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsTaxDetails> =
        z.object({});
}

/** @internal */
export const GetProductsProductsFieldType$ = z.nativeEnum(GetProductsProductsFieldType);

/** @internal */
export namespace GetProductsProductsCustomFields$ {
    export type Inbound = {
        id?: string | undefined;
        fieldName?: string | undefined;
        fieldValue?: string | undefined;
        fieldType?: GetProductsProductsFieldType | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsProductsCustomFields, z.ZodTypeDef, Inbound> =
        z
            .object({
                id: z.string().optional(),
                fieldName: z.string().optional(),
                fieldValue: z.string().optional(),
                fieldType: GetProductsProductsFieldType$.optional(),
            })
            .transform((v) => {
                return {
                    ...(v.id === undefined ? null : { id: v.id }),
                    ...(v.fieldName === undefined ? null : { fieldName: v.fieldName }),
                    ...(v.fieldValue === undefined ? null : { fieldValue: v.fieldValue }),
                    ...(v.fieldType === undefined ? null : { fieldType: v.fieldType }),
                };
            });

    export type Outbound = {
        id?: string | undefined;
        fieldName?: string | undefined;
        fieldValue?: string | undefined;
        fieldType?: GetProductsProductsFieldType | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetProductsProductsCustomFields
    > = z
        .object({
            id: z.string().optional(),
            fieldName: z.string().optional(),
            fieldValue: z.string().optional(),
            fieldType: GetProductsProductsFieldType$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.fieldName === undefined ? null : { fieldName: v.fieldName }),
                ...(v.fieldValue === undefined ? null : { fieldValue: v.fieldValue }),
                ...(v.fieldType === undefined ? null : { fieldType: v.fieldType }),
            };
        });
}

/** @internal */
export namespace GetProductsTax$ {
    export type Inbound = {
        taxCode?: string | undefined;
        taxable?: boolean | undefined;
        taxRate?: number | undefined;
        currency?: string | undefined;
        country?: string | undefined;
        region?: string | undefined;
        description?: string | undefined;
        taxAmount?: number | undefined;
        taxDetails?: GetProductsTaxDetails$.Inbound | undefined;
        customFields?: Array<GetProductsProductsCustomFields$.Inbound> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        active?: boolean | undefined;
        deleted?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsTax, z.ZodTypeDef, Inbound> = z
        .object({
            taxCode: z.string().optional(),
            taxable: z.boolean().optional(),
            taxRate: z.number().optional(),
            currency: z.string().optional(),
            country: z.string().optional(),
            region: z.string().optional(),
            description: z.string().optional(),
            taxAmount: z.number().optional(),
            taxDetails: z.lazy(() => GetProductsTaxDetails$.inboundSchema).optional(),
            customFields: z
                .array(z.lazy(() => GetProductsProductsCustomFields$.inboundSchema))
                .optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            active: z.boolean().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.taxCode === undefined ? null : { taxCode: v.taxCode }),
                ...(v.taxable === undefined ? null : { taxable: v.taxable }),
                ...(v.taxRate === undefined ? null : { taxRate: v.taxRate }),
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.country === undefined ? null : { country: v.country }),
                ...(v.region === undefined ? null : { region: v.region }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.taxAmount === undefined ? null : { taxAmount: v.taxAmount }),
                ...(v.taxDetails === undefined ? null : { taxDetails: v.taxDetails }),
                ...(v.customFields === undefined ? null : { customFields: v.customFields }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.active === undefined ? null : { active: v.active }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });

    export type Outbound = {
        taxCode?: string | undefined;
        taxable?: boolean | undefined;
        taxRate?: number | undefined;
        currency?: string | undefined;
        country?: string | undefined;
        region?: string | undefined;
        description?: string | undefined;
        taxAmount?: number | undefined;
        taxDetails?: GetProductsTaxDetails$.Outbound | undefined;
        customFields?: Array<GetProductsProductsCustomFields$.Outbound> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        active?: boolean | undefined;
        deleted?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsTax> = z
        .object({
            taxCode: z.string().optional(),
            taxable: z.boolean().optional(),
            taxRate: z.number().optional(),
            currency: z.string().optional(),
            country: z.string().optional(),
            region: z.string().optional(),
            description: z.string().optional(),
            taxAmount: z.number().optional(),
            taxDetails: z.lazy(() => GetProductsTaxDetails$.outboundSchema).optional(),
            customFields: z
                .array(z.lazy(() => GetProductsProductsCustomFields$.outboundSchema))
                .optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            active: z.boolean().optional(),
            deleted: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.taxCode === undefined ? null : { taxCode: v.taxCode }),
                ...(v.taxable === undefined ? null : { taxable: v.taxable }),
                ...(v.taxRate === undefined ? null : { taxRate: v.taxRate }),
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.country === undefined ? null : { country: v.country }),
                ...(v.region === undefined ? null : { region: v.region }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.taxAmount === undefined ? null : { taxAmount: v.taxAmount }),
                ...(v.taxDetails === undefined ? null : { taxDetails: v.taxDetails }),
                ...(v.customFields === undefined ? null : { customFields: v.customFields }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.active === undefined ? null : { active: v.active }),
                ...(v.deleted === undefined ? null : { deleted: v.deleted }),
            };
        });
}

/** @internal */
export namespace GetProductsLocalizations$ {
    export type Inbound = {
        locale?: string | undefined;
        title?: string | undefined;
        description?: string | undefined;
        metaTitle?: string | undefined;
        metaDescription?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsLocalizations, z.ZodTypeDef, Inbound> = z
        .object({
            locale: z.string().optional(),
            title: z.string().optional(),
            description: z.string().optional(),
            metaTitle: z.string().optional(),
            metaDescription: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.locale === undefined ? null : { locale: v.locale }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.metaTitle === undefined ? null : { metaTitle: v.metaTitle }),
                ...(v.metaDescription === undefined
                    ? null
                    : { metaDescription: v.metaDescription }),
            };
        });

    export type Outbound = {
        locale?: string | undefined;
        title?: string | undefined;
        description?: string | undefined;
        metaTitle?: string | undefined;
        metaDescription?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsLocalizations> = z
        .object({
            locale: z.string().optional(),
            title: z.string().optional(),
            description: z.string().optional(),
            metaTitle: z.string().optional(),
            metaDescription: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.locale === undefined ? null : { locale: v.locale }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.metaTitle === undefined ? null : { metaTitle: v.metaTitle }),
                ...(v.metaDescription === undefined
                    ? null
                    : { metaDescription: v.metaDescription }),
            };
        });
}

/** @internal */
export namespace GetProductsUnified$ {
    export type Inbound = {
        id?: string | undefined;
        title?: string | undefined;
        description?: string | undefined;
        prices?: Array<GetProductsPrices$.Inbound> | undefined;
        sku?: string | undefined;
        skuValidation?: GetProductsSkuValidation | undefined;
        images?: Array<GetProductsImages$.Inbound> | undefined;
        variants?: Array<GetProductsVariants$.Inbound> | undefined;
        options?: Array<GetProductsOptions$.Inbound> | undefined;
        categories?: Array<string> | undefined;
        tags?: Array<string> | undefined;
        vendor?: string | undefined;
        inventoryQuantity?: number | undefined;
        inventoryLocation?: GetProductsInventoryLocation$.Inbound | undefined;
        availableForSale?: boolean | undefined;
        dimensions?: GetProductsDimensions$.Inbound | undefined;
        weight?: number | undefined;
        weightUnit?: string | undefined;
        type?: string | undefined;
        metaTitle?: string | undefined;
        metaDescription?: string | undefined;
        seoKeywords?: Array<string> | undefined;
        slug?: string | undefined;
        customFields?: Array<GetProductsCustomFields$.Inbound> | undefined;
        isDownloadable?: boolean | undefined;
        downloadFiles?: Array<GetProductsDownloadFiles$.Inbound> | undefined;
        relatedProducts?: Array<string> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        publishedAt?: number | undefined;
        status?: GetProductsStatus | undefined;
        tax?: GetProductsTax$.Inbound | undefined;
        localizations?: Array<GetProductsLocalizations$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsUnified, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            title: z.string().optional(),
            description: z.string().optional(),
            prices: z.array(z.lazy(() => GetProductsPrices$.inboundSchema)).optional(),
            sku: z.string().optional(),
            skuValidation: GetProductsSkuValidation$.optional(),
            images: z.array(z.lazy(() => GetProductsImages$.inboundSchema)).optional(),
            variants: z.array(z.lazy(() => GetProductsVariants$.inboundSchema)).optional(),
            options: z.array(z.lazy(() => GetProductsOptions$.inboundSchema)).optional(),
            categories: z.array(z.string()).optional(),
            tags: z.array(z.string()).optional(),
            vendor: z.string().optional(),
            inventoryQuantity: z.number().optional(),
            inventoryLocation: z.lazy(() => GetProductsInventoryLocation$.inboundSchema).optional(),
            availableForSale: z.boolean().optional(),
            dimensions: z.lazy(() => GetProductsDimensions$.inboundSchema).optional(),
            weight: z.number().optional(),
            weightUnit: z.string().optional(),
            type: z.string().optional(),
            metaTitle: z.string().optional(),
            metaDescription: z.string().optional(),
            seoKeywords: z.array(z.string()).optional(),
            slug: z.string().optional(),
            customFields: z.array(z.lazy(() => GetProductsCustomFields$.inboundSchema)).optional(),
            isDownloadable: z.boolean().optional(),
            downloadFiles: z
                .array(z.lazy(() => GetProductsDownloadFiles$.inboundSchema))
                .optional(),
            relatedProducts: z.array(z.string()).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            publishedAt: z.number().optional(),
            status: GetProductsStatus$.optional(),
            tax: z.lazy(() => GetProductsTax$.inboundSchema).optional(),
            localizations: z
                .array(z.lazy(() => GetProductsLocalizations$.inboundSchema))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.prices === undefined ? null : { prices: v.prices }),
                ...(v.sku === undefined ? null : { sku: v.sku }),
                ...(v.skuValidation === undefined ? null : { skuValidation: v.skuValidation }),
                ...(v.images === undefined ? null : { images: v.images }),
                ...(v.variants === undefined ? null : { variants: v.variants }),
                ...(v.options === undefined ? null : { options: v.options }),
                ...(v.categories === undefined ? null : { categories: v.categories }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
                ...(v.vendor === undefined ? null : { vendor: v.vendor }),
                ...(v.inventoryQuantity === undefined
                    ? null
                    : { inventoryQuantity: v.inventoryQuantity }),
                ...(v.inventoryLocation === undefined
                    ? null
                    : { inventoryLocation: v.inventoryLocation }),
                ...(v.availableForSale === undefined
                    ? null
                    : { availableForSale: v.availableForSale }),
                ...(v.dimensions === undefined ? null : { dimensions: v.dimensions }),
                ...(v.weight === undefined ? null : { weight: v.weight }),
                ...(v.weightUnit === undefined ? null : { weightUnit: v.weightUnit }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.metaTitle === undefined ? null : { metaTitle: v.metaTitle }),
                ...(v.metaDescription === undefined
                    ? null
                    : { metaDescription: v.metaDescription }),
                ...(v.seoKeywords === undefined ? null : { seoKeywords: v.seoKeywords }),
                ...(v.slug === undefined ? null : { slug: v.slug }),
                ...(v.customFields === undefined ? null : { customFields: v.customFields }),
                ...(v.isDownloadable === undefined ? null : { isDownloadable: v.isDownloadable }),
                ...(v.downloadFiles === undefined ? null : { downloadFiles: v.downloadFiles }),
                ...(v.relatedProducts === undefined
                    ? null
                    : { relatedProducts: v.relatedProducts }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.publishedAt === undefined ? null : { publishedAt: v.publishedAt }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.tax === undefined ? null : { tax: v.tax }),
                ...(v.localizations === undefined ? null : { localizations: v.localizations }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        title?: string | undefined;
        description?: string | undefined;
        prices?: Array<GetProductsPrices$.Outbound> | undefined;
        sku?: string | undefined;
        skuValidation?: GetProductsSkuValidation | undefined;
        images?: Array<GetProductsImages$.Outbound> | undefined;
        variants?: Array<GetProductsVariants$.Outbound> | undefined;
        options?: Array<GetProductsOptions$.Outbound> | undefined;
        categories?: Array<string> | undefined;
        tags?: Array<string> | undefined;
        vendor?: string | undefined;
        inventoryQuantity?: number | undefined;
        inventoryLocation?: GetProductsInventoryLocation$.Outbound | undefined;
        availableForSale?: boolean | undefined;
        dimensions?: GetProductsDimensions$.Outbound | undefined;
        weight?: number | undefined;
        weightUnit?: string | undefined;
        type?: string | undefined;
        metaTitle?: string | undefined;
        metaDescription?: string | undefined;
        seoKeywords?: Array<string> | undefined;
        slug?: string | undefined;
        customFields?: Array<GetProductsCustomFields$.Outbound> | undefined;
        isDownloadable?: boolean | undefined;
        downloadFiles?: Array<GetProductsDownloadFiles$.Outbound> | undefined;
        relatedProducts?: Array<string> | undefined;
        createdAt?: number | undefined;
        updatedAt?: number | undefined;
        publishedAt?: number | undefined;
        status?: GetProductsStatus | undefined;
        tax?: GetProductsTax$.Outbound | undefined;
        localizations?: Array<GetProductsLocalizations$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsUnified> = z
        .object({
            id: z.string().optional(),
            title: z.string().optional(),
            description: z.string().optional(),
            prices: z.array(z.lazy(() => GetProductsPrices$.outboundSchema)).optional(),
            sku: z.string().optional(),
            skuValidation: GetProductsSkuValidation$.optional(),
            images: z.array(z.lazy(() => GetProductsImages$.outboundSchema)).optional(),
            variants: z.array(z.lazy(() => GetProductsVariants$.outboundSchema)).optional(),
            options: z.array(z.lazy(() => GetProductsOptions$.outboundSchema)).optional(),
            categories: z.array(z.string()).optional(),
            tags: z.array(z.string()).optional(),
            vendor: z.string().optional(),
            inventoryQuantity: z.number().optional(),
            inventoryLocation: z
                .lazy(() => GetProductsInventoryLocation$.outboundSchema)
                .optional(),
            availableForSale: z.boolean().optional(),
            dimensions: z.lazy(() => GetProductsDimensions$.outboundSchema).optional(),
            weight: z.number().optional(),
            weightUnit: z.string().optional(),
            type: z.string().optional(),
            metaTitle: z.string().optional(),
            metaDescription: z.string().optional(),
            seoKeywords: z.array(z.string()).optional(),
            slug: z.string().optional(),
            customFields: z.array(z.lazy(() => GetProductsCustomFields$.outboundSchema)).optional(),
            isDownloadable: z.boolean().optional(),
            downloadFiles: z
                .array(z.lazy(() => GetProductsDownloadFiles$.outboundSchema))
                .optional(),
            relatedProducts: z.array(z.string()).optional(),
            createdAt: z.number().optional(),
            updatedAt: z.number().optional(),
            publishedAt: z.number().optional(),
            status: GetProductsStatus$.optional(),
            tax: z.lazy(() => GetProductsTax$.outboundSchema).optional(),
            localizations: z
                .array(z.lazy(() => GetProductsLocalizations$.outboundSchema))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.title === undefined ? null : { title: v.title }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.prices === undefined ? null : { prices: v.prices }),
                ...(v.sku === undefined ? null : { sku: v.sku }),
                ...(v.skuValidation === undefined ? null : { skuValidation: v.skuValidation }),
                ...(v.images === undefined ? null : { images: v.images }),
                ...(v.variants === undefined ? null : { variants: v.variants }),
                ...(v.options === undefined ? null : { options: v.options }),
                ...(v.categories === undefined ? null : { categories: v.categories }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
                ...(v.vendor === undefined ? null : { vendor: v.vendor }),
                ...(v.inventoryQuantity === undefined
                    ? null
                    : { inventoryQuantity: v.inventoryQuantity }),
                ...(v.inventoryLocation === undefined
                    ? null
                    : { inventoryLocation: v.inventoryLocation }),
                ...(v.availableForSale === undefined
                    ? null
                    : { availableForSale: v.availableForSale }),
                ...(v.dimensions === undefined ? null : { dimensions: v.dimensions }),
                ...(v.weight === undefined ? null : { weight: v.weight }),
                ...(v.weightUnit === undefined ? null : { weightUnit: v.weightUnit }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.metaTitle === undefined ? null : { metaTitle: v.metaTitle }),
                ...(v.metaDescription === undefined
                    ? null
                    : { metaDescription: v.metaDescription }),
                ...(v.seoKeywords === undefined ? null : { seoKeywords: v.seoKeywords }),
                ...(v.slug === undefined ? null : { slug: v.slug }),
                ...(v.customFields === undefined ? null : { customFields: v.customFields }),
                ...(v.isDownloadable === undefined ? null : { isDownloadable: v.isDownloadable }),
                ...(v.downloadFiles === undefined ? null : { downloadFiles: v.downloadFiles }),
                ...(v.relatedProducts === undefined
                    ? null
                    : { relatedProducts: v.relatedProducts }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
                ...(v.updatedAt === undefined ? null : { updatedAt: v.updatedAt }),
                ...(v.publishedAt === undefined ? null : { publishedAt: v.publishedAt }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.tax === undefined ? null : { tax: v.tax }),
                ...(v.localizations === undefined ? null : { localizations: v.localizations }),
            };
        });
}

/** @internal */
export namespace GetProductsPassthrough$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetProductsPassthrough, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsPassthrough> =
        z.object({});
}

/** @internal */
export namespace GetProductsCache$ {
    export type Inbound = {
        hit?: boolean | undefined;
        ttl?: number | undefined;
        key?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsCache, z.ZodTypeDef, Inbound> = z
        .object({
            hit: z.boolean().optional(),
            ttl: z.number().int().optional(),
            key: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.hit === undefined ? null : { hit: v.hit }),
                ...(v.ttl === undefined ? null : { ttl: v.ttl }),
                ...(v.key === undefined ? null : { key: v.key }),
            };
        });

    export type Outbound = {
        hit?: boolean | undefined;
        ttl?: number | undefined;
        key?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsCache> = z
        .object({
            hit: z.boolean().optional(),
            ttl: z.number().int().optional(),
            key: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.hit === undefined ? null : { hit: v.hit }),
                ...(v.ttl === undefined ? null : { ttl: v.ttl }),
                ...(v.key === undefined ? null : { key: v.key }),
            };
        });
}

/** @internal */
export namespace GetProductsMeta$ {
    export type Inbound = {
        timestamp?: number | undefined;
        latency?: number | undefined;
        platformRateLimitRemaining?: number | undefined;
        rateLimitRemaining?: number | undefined;
        cache?: GetProductsCache$.Inbound | undefined;
        transactionKey?: string | undefined;
        txn?: string | undefined;
        platform?: string | undefined;
        platformVersion?: string | undefined;
        connectionDefinitionKey?: string | undefined;
        action?: string | undefined;
        commonModel?: string | undefined;
        commonModelVersion?: string | undefined;
        connectionKey?: string | undefined;
        hash?: string | undefined;
        heartbeats?: Array<string> | undefined;
        totalTransactions?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsMeta, z.ZodTypeDef, Inbound> = z
        .object({
            timestamp: z.number().int().optional(),
            latency: z.number().int().optional(),
            platformRateLimitRemaining: z.number().int().optional(),
            rateLimitRemaining: z.number().int().optional(),
            cache: z.lazy(() => GetProductsCache$.inboundSchema).optional(),
            transactionKey: z.string().optional(),
            txn: z.string().optional(),
            platform: z.string().optional(),
            platformVersion: z.string().optional(),
            connectionDefinitionKey: z.string().optional(),
            action: z.string().optional(),
            commonModel: z.string().optional(),
            commonModelVersion: z.string().optional(),
            connectionKey: z.string().optional(),
            hash: z.string().optional(),
            heartbeats: z.array(z.string()).optional(),
            totalTransactions: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.timestamp === undefined ? null : { timestamp: v.timestamp }),
                ...(v.latency === undefined ? null : { latency: v.latency }),
                ...(v.platformRateLimitRemaining === undefined
                    ? null
                    : { platformRateLimitRemaining: v.platformRateLimitRemaining }),
                ...(v.rateLimitRemaining === undefined
                    ? null
                    : { rateLimitRemaining: v.rateLimitRemaining }),
                ...(v.cache === undefined ? null : { cache: v.cache }),
                ...(v.transactionKey === undefined ? null : { transactionKey: v.transactionKey }),
                ...(v.txn === undefined ? null : { txn: v.txn }),
                ...(v.platform === undefined ? null : { platform: v.platform }),
                ...(v.platformVersion === undefined
                    ? null
                    : { platformVersion: v.platformVersion }),
                ...(v.connectionDefinitionKey === undefined
                    ? null
                    : { connectionDefinitionKey: v.connectionDefinitionKey }),
                ...(v.action === undefined ? null : { action: v.action }),
                ...(v.commonModel === undefined ? null : { commonModel: v.commonModel }),
                ...(v.commonModelVersion === undefined
                    ? null
                    : { commonModelVersion: v.commonModelVersion }),
                ...(v.connectionKey === undefined ? null : { connectionKey: v.connectionKey }),
                ...(v.hash === undefined ? null : { hash: v.hash }),
                ...(v.heartbeats === undefined ? null : { heartbeats: v.heartbeats }),
                ...(v.totalTransactions === undefined
                    ? null
                    : { totalTransactions: v.totalTransactions }),
            };
        });

    export type Outbound = {
        timestamp?: number | undefined;
        latency?: number | undefined;
        platformRateLimitRemaining?: number | undefined;
        rateLimitRemaining?: number | undefined;
        cache?: GetProductsCache$.Outbound | undefined;
        transactionKey?: string | undefined;
        txn?: string | undefined;
        platform?: string | undefined;
        platformVersion?: string | undefined;
        connectionDefinitionKey?: string | undefined;
        action?: string | undefined;
        commonModel?: string | undefined;
        commonModelVersion?: string | undefined;
        connectionKey?: string | undefined;
        hash?: string | undefined;
        heartbeats?: Array<string> | undefined;
        totalTransactions?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsMeta> = z
        .object({
            timestamp: z.number().int().optional(),
            latency: z.number().int().optional(),
            platformRateLimitRemaining: z.number().int().optional(),
            rateLimitRemaining: z.number().int().optional(),
            cache: z.lazy(() => GetProductsCache$.outboundSchema).optional(),
            transactionKey: z.string().optional(),
            txn: z.string().optional(),
            platform: z.string().optional(),
            platformVersion: z.string().optional(),
            connectionDefinitionKey: z.string().optional(),
            action: z.string().optional(),
            commonModel: z.string().optional(),
            commonModelVersion: z.string().optional(),
            connectionKey: z.string().optional(),
            hash: z.string().optional(),
            heartbeats: z.array(z.string()).optional(),
            totalTransactions: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.timestamp === undefined ? null : { timestamp: v.timestamp }),
                ...(v.latency === undefined ? null : { latency: v.latency }),
                ...(v.platformRateLimitRemaining === undefined
                    ? null
                    : { platformRateLimitRemaining: v.platformRateLimitRemaining }),
                ...(v.rateLimitRemaining === undefined
                    ? null
                    : { rateLimitRemaining: v.rateLimitRemaining }),
                ...(v.cache === undefined ? null : { cache: v.cache }),
                ...(v.transactionKey === undefined ? null : { transactionKey: v.transactionKey }),
                ...(v.txn === undefined ? null : { txn: v.txn }),
                ...(v.platform === undefined ? null : { platform: v.platform }),
                ...(v.platformVersion === undefined
                    ? null
                    : { platformVersion: v.platformVersion }),
                ...(v.connectionDefinitionKey === undefined
                    ? null
                    : { connectionDefinitionKey: v.connectionDefinitionKey }),
                ...(v.action === undefined ? null : { action: v.action }),
                ...(v.commonModel === undefined ? null : { commonModel: v.commonModel }),
                ...(v.commonModelVersion === undefined
                    ? null
                    : { commonModelVersion: v.commonModelVersion }),
                ...(v.connectionKey === undefined ? null : { connectionKey: v.connectionKey }),
                ...(v.hash === undefined ? null : { hash: v.hash }),
                ...(v.heartbeats === undefined ? null : { heartbeats: v.heartbeats }),
                ...(v.totalTransactions === undefined
                    ? null
                    : { totalTransactions: v.totalTransactions }),
            };
        });
}

/** @internal */
export namespace GetProductsPagination$ {
    export type Inbound = {
        cursor?: string | undefined;
        limit?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsPagination, z.ZodTypeDef, Inbound> = z
        .object({
            cursor: z.string().optional(),
            limit: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.cursor === undefined ? null : { cursor: v.cursor }),
                ...(v.limit === undefined ? null : { limit: v.limit }),
            };
        });

    export type Outbound = {
        cursor?: string | undefined;
        limit?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsPagination> = z
        .object({
            cursor: z.string().optional(),
            limit: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.cursor === undefined ? null : { cursor: v.cursor }),
                ...(v.limit === undefined ? null : { limit: v.limit }),
            };
        });
}

/** @internal */
export namespace GetProductsResponseBody$ {
    export type Inbound = {
        status?: string | undefined;
        statusCode?: GetProductsStatusCode | undefined;
        unified?: Array<GetProductsUnified$.Inbound> | undefined;
        passthrough?: GetProductsPassthrough$.Inbound | undefined;
        meta?: GetProductsMeta$.Inbound | undefined;
        pagination?: GetProductsPagination$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            status: z.string().optional(),
            statusCode: GetProductsStatusCode$.optional(),
            unified: z.array(z.lazy(() => GetProductsUnified$.inboundSchema)).optional(),
            passthrough: z.lazy(() => GetProductsPassthrough$.inboundSchema).optional(),
            meta: z.lazy(() => GetProductsMeta$.inboundSchema).optional(),
            pagination: z.lazy(() => GetProductsPagination$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.statusCode === undefined ? null : { statusCode: v.statusCode }),
                ...(v.unified === undefined ? null : { unified: v.unified }),
                ...(v.passthrough === undefined ? null : { passthrough: v.passthrough }),
                ...(v.meta === undefined ? null : { meta: v.meta }),
                ...(v.pagination === undefined ? null : { pagination: v.pagination }),
            };
        });

    export type Outbound = {
        status?: string | undefined;
        statusCode?: GetProductsStatusCode | undefined;
        unified?: Array<GetProductsUnified$.Outbound> | undefined;
        passthrough?: GetProductsPassthrough$.Outbound | undefined;
        meta?: GetProductsMeta$.Outbound | undefined;
        pagination?: GetProductsPagination$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsResponseBody> = z
        .object({
            status: z.string().optional(),
            statusCode: GetProductsStatusCode$.optional(),
            unified: z.array(z.lazy(() => GetProductsUnified$.outboundSchema)).optional(),
            passthrough: z.lazy(() => GetProductsPassthrough$.outboundSchema).optional(),
            meta: z.lazy(() => GetProductsMeta$.outboundSchema).optional(),
            pagination: z.lazy(() => GetProductsPagination$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.statusCode === undefined ? null : { statusCode: v.statusCode }),
                ...(v.unified === undefined ? null : { unified: v.unified }),
                ...(v.passthrough === undefined ? null : { passthrough: v.passthrough }),
                ...(v.meta === undefined ? null : { meta: v.meta }),
                ...(v.pagination === undefined ? null : { pagination: v.pagination }),
            };
        });
}

/** @internal */
export namespace GetProductsResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: GetProductsResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetProductsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetProductsResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: GetProductsResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetProductsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetProductsResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
